version: '2'

services:
  postgres:
    build: images/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DBS: "dativebase"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '127.0.0.1:5432:5432'
  migrator:
    build:
      context: .
      dockerfile: ./migrator.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'jdbc:postgresql://postgres:5432/dativebase'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: ''
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/conf.d/dativebase.conf:/etc/nginx/conf.d/dativebase.conf:ro"
      - "./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    expose:
      - "80"
      - "8000"
    ports:
      - "63000:80"
      - "63001:8000"
